### ISSUE TITLE
Use MooseX::Method::Signatures

### ISSUE THREAD

**Issue by avar** [hinrik/hailo#11]
It's [delicious](http://search.cpan.org/~flora/MooseX-Method-Signatures-0.29/lib/MooseX/Method/Signatures.pm)

**Comment by hinrik** [comment]
Indeed it is. But I recall reading somewhere that it may inflict a significant runtime performance penalty. Maybe try using it everywhere and running a mass import/reply under NYTProf to see if it's significant?

**Comment by hinrik** [comment]
This turned out to be increadibly slow. I guess we'll have to wait for Perl 6...
