### ISSUE TITLE
Command-line conversation

### ISSUE THREAD

**Issue by hinrik** [hinrik/hailo#13]
When "hailo" is invoked without `--learn`, `--reply`, or `--train`, it should present an interface for conversing with the specified brain.

E.g. something like:
    $ hailo -b /tmp/brain.sqlite
    Engaging in conversation with "/tmp/brain.sqlite". EOF (or CTRL+C) will quit.
    input> Why hello there.
    output> ...

**Comment by avar** [comment]
This is now implemented as Hailo::UI::ReadLine
