### ISSUE TITLE
Use grammars in the Word tokenizer

### ISSUE THREAD

**Issue by hinrik** [hinrik/hailo#16]
Words.pm uses a few hacky regexes to capitalize words. It needs quite a bit of context to decide which words to capitalize, so it does it in three passes. It might be more efficient to use some of 5.10's grammar features instead.

**Comment by avar** [comment]
I tried this at one point and I got some errors which indicated internal errors in the regex engine. Perhaps I was doing something wrong.

**Comment by avar** [comment]
Moved to /BUGS
