### ISSUE TITLE
Not all command-line options use dashes

### ISSUE THREAD

**Issue by hinrik** [hinrik/hailo#17]
For some reason, the `learn_reply` option is presented verbatim in `--help`. MooseX::Getopt::Dashes should be converting the underscore to a dash. This works fine for `--ui-args` and other options. Maybe it doesn't work because the `learn_reply_str` attribute has `learn_reply` set as a `cmd_flag`, whereas the `--ui_args` option and others derive their name directly from the attribute name (i.e. no `cmd_flag` is set). If so, then I guess it's a bug in MooseX::Getopt::Dashes.

**Comment by avar** [comment]
MooseX::Getopt::Dashes doesn't touch the command flags if $attr->has_cmd_flag, consequently this means we're not actually using MX::Go::D for much, but that's another issue.
