### ISSUE TITLE
Train from non-file

### ISSUE THREAD

**Issue by hinrik** [hinrik/hailo#19]
It would be nice if train() also accepted a filehandle or an array reference instead of a filename, to accommodate those who already have an open filehandle or have an array of lines they want to train on.

**Comment by avar** [comment]
count_lines() doesn't work on filehandles, we need to work around that.

**Comment by avar** [comment]
Tests added in bd2b196b28d91474136a61f7a2d28edb523d5d02

**Comment by avar** [comment]
Fixed in c8efbc101cdf4348f1a74ca882f51ac870f82275

**Comment by hinrik** [comment]
You didn't add support for array references, but that has now been done in 39393e38feef654ba3bc2bcb6f727368282c9c07.
