### ISSUE TITLE
Chicken and egg problem when getting markov order from DB

### ISSUE THREAD

**Issue by hinrik** [hinrik/hailo#22]
When an existing SQL database has a Markov order different from the 'order' object attribute, the backend will generate incorrect SQL statements. This is because the statements used to retrieve the markov order from the database are prepared at the same time as the other statements, so the order used in all SQL statements has been set before the order has been retrieved from the database.

**Comment by avar** [comment]
zOMG failing tests plz!

**Comment by hinrik** [comment]
You can has fail: bcfcbe3766c08ac9f01cc0d696b92270337fc8f1

**Comment by hinrik** [comment]
Fixed in 5da0b515d14fcffe0adb6d5194eefed541b5adca
