### ISSUE TITLE
Training progress is non-linear

### ISSUE THREAD

**Issue by hinrik** [hinrik/hailo#23]
Our use of Term::ProgressBar assumes that the time estimation for training is linear, but this is not so. It gets slower with time. We should do something to make the time estimate more accurate.

**Comment by avar** [comment]
File a bug upstream!

I for one have no interest in writing the 54325th progress bar implementation.

**Comment by avar** [comment]
Consider this solved in 02fa4631fe777d5a51878f144fdb0ad0b15defa3
