### ISSUE TITLE
Reduce the memory usage

### ISSUE THREAD

**Issue by hinrik** [hinrik/hailo#27]
Hailo uses quite a bit of memory. As of Hailo 0.16, on a x86-64 host, our failo brain takes about 92MB on disk and 124MB in memory, while an empty Hailo process takes 23MB. That is, a total of 147MB with our DB in memory.

The DB schema is quite optimized now, so it's using about half the amount space on disk that MegaHAL would use, and much less than half when loaded into memory. It might be possible to optimize it some more but at the moment I don't see how.

The rest of the memory usage (23MB) can be attributed to the modules we use. Maybe we could do without some of those.

**Comment by hinrik** [comment]
Those 23MB have been brought down to 19MB by dropping Log::Log4perl and loading some other dependencies only on demand. I doubt we'll be able to go much lower without doing something drastic like making the app compatible with Mouse.

**Comment by avar** [comment]
We've pretty much killed everything we can without rewriting Hailo not to use Moose, also in-memory isn't the default anymore so this isn't really a problem.
