### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by avar** [hinrik/hailo#30]
[This is our current test coverage](http://v.nix.is/~avar/cover_db/coverage.html) pulled from avar/hailo/master and updated every 6 hours.

**Comment by hinrik** [comment]
The ReadLine UI is currently lacking tests. We could use [Test::Expect](http://search.cpan.org/perldoc?Test::Expect) for that.

**Comment by avar** [comment]
solved, opening more specific bugs for specific issues.
