### ISSUE TITLE
Nuke has() accessors for Hailo.pm and use is => 'bare'

### ISSUE THREAD

**Issue by avar** [hinrik/hailo#7]
Hailo->new( storage_class => ... ) looks ugly, let's use ->new( storage => ... ) instead. This means we can't set these at runtime but who cares?

**Comment by hinrik** [comment]
The reason we don't use "storage" is because it conflicts with the name of the command line option. I changed it to "storage_class" because of that.

**Comment by avar** [comment]
I know. But they wouldn't conflict with is=>bare, however not being able to change them at runtime sucks more than the ugly names so WONTFIX.
